[package]
name = "pad-motion"
version = "0.1.0"
authors = ["zduny <dzduniak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pad_motion"

[dependencies]
byteorder = "*"
crc = "*"
rand = "*"
crossbeam-queue = "*"

[dev-dependencies]
ctrlc = "*"
gilrs = "*"
multiinput = "*"
